productsSample = [
    "Bạn có sẵn iPhone mới nhất không?",
    "Giá của Samsung Galaxy S21 là bao nhiêu?",
    "OnePlus 9 Pro có màu xanh không?",
    "Thông số kỹ thuật của Google Pixel 6 là gì?",
    "Huawei P50 Pro có sẵn ở cửa hàng của bạn không?",
    "iPhone 13 có những màu gì?",
    "Có giảm giá nào cho Samsung Galaxy Note 20 không?",
    "Sony Xperia 1 III có sẵn không?",
    "Cửa hàng của bạn có Google Pixel mới nhất không?",
    "Có chương trình khuyến mãi nào cho OnePlus Nord không?",
    "Dung lượng lưu trữ của Samsung Galaxy S21 là bao nhiêu?",
    "iPhone SE 2022 có sẵn không?",
    "Sự khác biệt về giá giữa iPhone 12 và 13 là gì?",
    "Motorola Edge 20 có sẵn không?",
    "Google Pixel 6 Pro có sẵn ở cửa hàng của bạn không?",
    "Bạn có bán Xiaomi Mi 11 không?",
    "Có chương trình ưu đãi nào cho Samsung Galaxy Z Fold 3 không?",
    "Oppo Find X3 Pro có sẵn không?",
    "Các tính năng của iPhone 13 Pro là gì?",
    "LG Wing có sẵn không?",
    "Nokia 8.3 5G có sẵn không?",
    "Asus ROG Phone 5 có sẵn không?",
    "Bạn có Realme GT không?",
    "Vivo X60 Pro có sẵn không?",
    "Bạn có Honor 50 không?",
    "Tuổi thọ pin của Samsung Galaxy A52 là bao nhiêu?",
    "ZTE Axon 30 có sẵn không?",
    "Bạn có BlackBerry KEY2 không?",
    "Kích thước màn hình của iPhone 13 Mini là bao nhiêu?",
    "Bạn có TCL 20 Pro 5G không?",
    "Nokia XR20 có sẵn ở cửa hàng của bạn không?",
    "Giá của Samsung Galaxy S20 FE là bao nhiêu?",
    "Bạn có iPhone 12 Pro Max không?",
    "Redmi Note 10 Pro có sẵn không?",
    "Sự khác biệt giữa iPhone 12 và iPhone 13 là gì?",
    "Bạn có Sony Xperia 5 II không?",
    "Thời gian bảo hành của Samsung Galaxy S21 là bao lâu?",
    "Google Pixel 5a có sẵn không?",
    "Bạn có OnePlus 8T không?",
    "Giá của iPhone 13 Pro Max là bao nhiêu?",
    "Samsung Galaxy Z Flip 3 có sẵn không?",
    "Thông số kỹ thuật của Oppo Reno6 Pro là gì?",
    "Bạn có Vivo V21 không?",
    "Motorola Moto G100 có sẵn không?",
    "Bạn có Huawei Mate 40 Pro không?",
    "Realme 8 Pro có sẵn ở cửa hàng của bạn không?",
    "Asus Zenfone 8 có sẵn không?",
    "LG Velvet có sẵn không?",
    "Dung lượng lưu trữ của iPhone 12 là bao nhiêu?",
    "Bạn có Honor Magic 3 không?",
    "Xiaomi Mi 11 Ultra có sẵn không?"
]


chitchatSample = [
    "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?"
]